# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-10 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_backend_django', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='test',
        ),
    ]
