# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-10 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_backend_django', '0002_remove_todoitem_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='test',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
