# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-10 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_backend_django', '0003_todoitem_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='test',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
