# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-10 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_backend_django', '0004_auto_20191209_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='label',
            field=models.ManyToManyField(to='todo_backend_django.Label'),
        ),
    ]
