# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-10 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_backend_django', '0005_auto_20191210_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='label',
            new_name='labels',
        ),
    ]
